import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 *
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - Provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined
 * here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    unifiedSidebar: [
        {
            className: "sb-doc-overview",
            id: "index",
            label: "🏁 Overview",
            type: "doc",
        },
        {
            className: "sb-cat-frontend",
            collapsed: true,
            customProps: { badge: "api" },
            items: [{ dirName: "src", type: "autogenerated" }],
            label: "🧩 Frontend (React)",
            link: {
                description: "Components, hooks, stores, utilities.",
                title: "Frontend (React) API",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-backend",
            collapsed: true,
            customProps: { badge: "api" },
            items: [{ dirName: "electron", type: "autogenerated" }],
            label: "⚙️ Backend (Electron)",
            link: {
                description: "Main process services, managers, IPC handlers.",
                title: "Backend (Electron) API",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-shared",
            collapsed: true,
            customProps: { badge: "api" },
            items: [{ dirName: "shared", type: "autogenerated" }],
            label: "🔗 Shared Code",
            link: {
                description: "Shared types, utilities, validation logic.",
                title: "Shared Code API",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-internal",
            collapsed: true,
            customProps: { badge: "internal" },
            items: [
                // We rely on documents autogenerated tree; specific deep links can be front-matter ordered.
                {
                    dirName: "documents/docs/Architecture",
                    type: "autogenerated",
                },
            ],
            label: "🛠 Advanced Internals",
            link: {
                description:
                    "Architecture decisions, patterns, internal tooling.",
                title: "Advanced / Internal",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-guides",
            collapsed: true,
            customProps: { badge: "core" },
            items: [
                {
                    dirName: "documents/docs/Guides",
                    type: "autogenerated",
                },
            ],
            label: "📚 Guides & Package Docs",
            link: {
                description:
                    "Start here: environment setup, quick starts, and troubleshooting resources.",
                title: "Guides & Package Docs",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-charts",
            collapsed: true,
            customProps: { badge: "visual" },
            items: [
                {
                    id: "documents/docs/InteractiveCharts/system-architecture",
                    label: "🏗️ System Architecture",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/monitoring-workflows",
                    label: "🔄 Monitoring Workflows",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/data-models",
                    label: "🗄️ Data Models",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/deployment-infrastructure",
                    label: "🚀 Deployment & Infrastructure",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/performance-metrics",
                    label: "📊 Performance Metrics",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/event-system",
                    label: "📣 Event System",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/ipc-communication",
                    label: "🔌 IPC Communication",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/service-container",
                    label: "🧩 Service Container",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/error-handling",
                    label: "🧯 Error Handling",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/testing-architecture",
                    label: "🧪 Testing Architecture",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/engineering-tooling",
                    label: "🧰 Engineering Tooling",
                    type: "doc",
                },
                {
                    id: "documents/docs/InteractiveCharts/README",
                    label: "📎 Charts Index",
                    type: "doc",
                },
            ],
            label: "📈 Interactive Charts",
            link: {
                description:
                    "Interactive Mermaid diagrams showcasing system architecture, workflows, and data models.",
                title: "Interactive Charts & Diagrams",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-blog",
            collapsed: true,
            customProps: { badge: "blog" },
            items: [
                {
                    href: "/Uptime-Watcher/blog",
                    label: "📰 Blog Home",
                    type: "link",
                },
            ],
            label: "📰 Blog",
            link: {
                description:
                    "Development updates, deep dives, and release notes.",
                title: "Blog",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-tsdoc",
            collapsed: true,
            customProps: { badge: "docs" },
            items: [
                {
                    dirName: "documents/docs/TSDoc",
                    type: "autogenerated",
                },
            ],
            label: "📝 TSDoc Documentation",
            link: {
                description:
                    "TypeScript documentation standards, tags, and best practices for code documentation.",
                title: "TSDoc Documentation",
                type: "generated-index",
            },
            type: "category",
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
