import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 *
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - Provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined
 * here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    unifiedSidebar: [
        {
            className: "sb-doc-overview",
            id: "index",
            label: "🏁 Overview",
            type: "doc",
        },
        {
            className: "sb-cat-frontend",
            collapsed: true,
            customProps: { badge: "api" },
            items: [{ dirName: "src", type: "autogenerated" }],
            label: "🧩 Frontend (React)",
            link: {
                description: "Components, hooks, stores, utilities.",
                title: "Frontend (React) API",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-backend",
            collapsed: true,
            customProps: { badge: "api" },
            items: [{ dirName: "electron", type: "autogenerated" }],
            label: "⚙️ Backend (Electron)",
            link: {
                description: "Main process services, managers, IPC handlers.",
                title: "Backend (Electron) API",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-shared",
            collapsed: true,
            customProps: { badge: "api" },
            items: [{ dirName: "shared", type: "autogenerated" }],
            label: "🔗 Shared Code",
            link: {
                description: "Shared types, utilities, validation logic.",
                title: "Shared Code API",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-internal",
            collapsed: true,
            customProps: { badge: "internal" },
            items: [
                // We rely on documents autogenerated tree; specific deep links can be front-matter ordered.
                {
                    dirName: "documents/docs/Architecture",
                    type: "autogenerated",
                },
            ],
            label: "🛠 Advanced Internals",
            link: {
                description:
                    "Architecture decisions, patterns, internal tooling.",
                title: "Advanced / Internal",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-guides",
            collapsed: true,
            customProps: { badge: "core" },
            items: [
                {
                    dirName: "documents/docs/Guides",
                    type: "autogenerated",
                },
                {
                    dirName: "documents/docs/Packages",
                    type: "autogenerated",
                },
            ],
            label: "📚 Guides & Package Docs",
            link: {
                description:
                    "Start here: environment setup, quick starts, and troubleshooting resources.",
                title: "Guides & Package Docs",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-tsdoc",
            collapsed: true,
            customProps: { badge: "docs" },
            items: [
                {
                    dirName: "documents/docs/TSDoc",
                    type: "autogenerated",
                },
                "documents/@alpha",
                "documents/@beta",
                "documents/@decorator",
                "documents/@defaultValue",
                "documents/@deprecated",
                "documents/@eventProperty",
                "documents/@example",
                "documents/@experimental",
                "documents/@inheritDoc",
                "documents/@internal",
                "documents/@label",
                "documents/@link",
                "documents/@override",
                "documents/@packageDocumentation",
                "documents/@param",
                "documents/@privateRemarks",
                "documents/@public",
                "documents/@readonly",
                "documents/@remarks",
                "documents/@returns",
                "documents/@sealed",
                "documents/@see",
                "documents/@throws",
                "documents/@typeParam",
                "documents/@virtual",
            ],
            label: "📝 TSDoc Documentation",
            link: {
                description:
                    "TypeScript documentation standards, tags, and best practices for code documentation.",
                title: "TSDoc Documentation",
                type: "generated-index",
            },
            type: "category",
        },
    ],
};

export default sidebars;
